### ISSUE TITLE
Structs use comma now

### ISSUE THREAD

**Issue by blessedbythestorm** [dparnell/intellij-wgsl#20] opened 2022-05-28 15:03 UTC
In IDE I keep getting: ```WGSLTokenType.SEMICOLON expected, got ','``` at the end of a struct field.

WGSL standard now defines shader structs with a comma rather than a semicolon.

**Comment by dparnell** [comment] 2022-05-29 00:00
This is a duplicate of #18 . I am currently working on a fix

**Closed as completed by dparnell** 2022-05-29 00:00 UTC
